<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Version>1.1.2</Version>
		<TargetFramework>net8.0</TargetFramework>
		<Platforms>AnyCPU;x86</Platforms>
	</PropertyGroup>
	
	<ItemGroup>
	 	<Reference Include="configlib">
		<HintPath>$(VSLIBS)/dlls/configlib.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="VintagestoryAPI">
			<HintPath>$(VINTAGE_STORY)/VintagestoryAPI.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="VintagestorySurvival">
			<HintPath>$(VINTAGE_STORY)/Mods/VSSurvivalMod.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Newtonsoft.Json">
      		<HintPath>$(VINTAGE_STORY)\Lib\Newtonsoft.Json.dll</HintPath>
      		<Private>false</Private>
    	</Reference>
	</ItemGroup>

	<ItemGroup>
		<None Include="LICENSE" CopyToOutputDirectory="PreserveNewest" />
		<None Include="modicon.png" CopyToOutputDirectory="PreserveNewest" />
		<None Include="modinfo.json" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="./assets/**"  >
			<Link>assets/%(RecursiveDir)%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<Target Name="Package" AfterTargets="PostBuildEvent" Condition="'$(Configuration)' == 'Release'">
		<ZipDirectory DestinationFile="bin/$(TargetName)_$(Version).zip" SourceDirectory="$(TargetDir)" Overwrite="true" />
	</Target>
	
</Project>
